- name: Add kubeadm on SN
  yum_repository:
          name: kube
          description: K8s repo
          baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
          enabled: 1
          gpgcheck: 1
          gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg  https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Docker & kubeadm on SN
  package:
          name:
            - docker
            - kubeadm
            - iproute-tc
          state: present

- name: Enabling docker $ kubelet
  copy:
          dest: /etc/docker/daemon.json
          content: |
              {
                      "exec-opts": ["native.cgroupdriver=systemd"]
              }

- name: Restart docker & kubelet
  service:
          name: docker
          state: restarted

- name: Update IP tables
  copy:
          dest: /etc/sysctl.d/k8s.conf
          content: |
               net.bridge.bridge-nf-call-ip6tables = 1
               net.bridge-bridge-nf-call-iptables = 1

- name: Reload sysctl
  command: sysctl --system

- name: Join the MN
  command: "{{ hostvars[groups['ec2_master'][0]]['token']['stdout'] }}"

- name: Cleaning caches on RAM
  shell: ech0 3 > /proc/sys/vm/drop_caches






